<?php

namespace ICT\Core\Test;

use ICT\Core\Contact;
use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-12-05 at 12:58:29.
 */
class ContactTest extends PHPUnit_Framework_TestCase
{

  /**
   * @var Contact
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new Contact;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
    unset($this->object);
  }

  /**
   * @covers Contact::construct_from_array
   * @todo   Implement testConstruct_from_array().
   */
  public function testConstruct_from_array()
  {
    $string = true;
    $this->assertTrue($string);
  }

  /**
   * @covers Contact::token_get
   * @todo   Implement testToken_get().
   */
  public function testToken_get()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Contact::search
   * @todo   Implement testSearch().
   */
  public function testSearch()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Contact::delete
   * @todo   Implement testDelete().
   */
  public function testDelete()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Contact::__isset
   * @todo   Implement test__isset().
   */
  public function test__isset()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Contact::__get
   * @todo   Implement test__get().
   */
  public function test__get()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Contact::__set
   * @todo   Implement test__set().
   */
  public function test__set()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Contact::email_to_phone
   * @todo   Implement testEmail_to_phone().
   */
  public function testEmail_to_phone()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Contact::phone_to_email
   * @todo   Implement testPhone_to_email().
   */
  public function testPhone_to_email()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Contact::save
   * @todo   Implement testSave().
   */
  public function testSave()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

}